[package]
name = "proto"
edition = "2021"
version = "0.1.0"

[dependencies]
prost = "0.12.3"
serde = { version = "1.0.197", features = ["derive"] }
sha2 = "0.10.8"
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
