name: Market CI

on:
  push:
    branches: [ "*" ]
    paths:
      - market/**
  pull_request:
    branches: [ "*" ]
    paths:
      - market/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install protobuf-compiler
      run: sudo apt update && sudo apt install -y protobuf-compiler
    - name: Cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/market/.cargo/bin/
          ~/market/.cargo/registry/index/
          ~/market/.cargo/registry/cache/
          ~/market/.cargo/git/db/
          market/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Build
      working-directory: market
      run: cargo build --verbose
    - name: Test
      working-directory: market
      run: cargo test --verbose

  format:
    name: Format Market
    if: ${{ !contains(github.event.head_commit.message, 'GITHUB ACTIONS') }}
    uses: ./.github/workflows/fmt.yml # use current repo's fmt.yml
    with:
      config-path: "market"
    