name: Peernode CI

on:
  push:
    branches: [ "*" ]
    paths:
      - peernode/**
  pull_request:
    branches: [ "*" ]
    paths:
      - peernode/**
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install protobuf-compiler
      run: sudo apt update && sudo apt install -y protobuf-compiler
    - name: Cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/peernode/.cargo/bin/
          ~/peernode/.cargo/registry/index/
          ~/peernode/.cargo/registry/cache/
          ~/peernode/.cargo/git/db/
          peernode/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Build
      working-directory: peernode
      run: cargo build --verbose
    - name: Test
      working-directory: peernode
      run: cargo test --verbose

#    - name: Start server and run sea pig tests
#      working-directory: peernode
#      run: |
#        cargo run --bin peer-node-server -F test_local_market &
#        sleep 5 &&
#        cargo test seapig_test --verbose -- --test-threads=1 --ignored
#    - name: Start server and run bubble guppies tests
#      working-directory: peernode
#      run: |
#        cargo build --bin peer-node-server -F test_local_market &&
#        cargo run --bin peer-node-server -F test_local_market &
#        sleep 10 &&
#        cargo test bubbleguppies_test --verbose -- --test-threads=1 --ignored

  format:
    name: Format Peernode
    needs: build
    if: ${{ !contains(github.event.head_commit.message, 'GITHUB ACTIONS') }}
    uses: ./.github/workflows/fmt.yml # use current repo's fmt.yml
    with:
      config-path: "peernode"
